server:
  host: "localhost:30124"
  type: "protobuffer"
  protobuffer:
    docs: "connector.docsHandler.docs"
    pushinfo:
      routes:
        - "connector.playerHandler.matchfound"
      protos:
        - "protos.FindMatchPush"
