version: '3'
services:
  nats:
    image: nats
    ports:
      - 4222:4222
  etcd:
    image: appcelerator/etcd
    ports:
      - 2379:2379
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    ports:
      - 9010:6379

